import { chmodSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { PLUGIN_ID } from "./paths.ts";
import type { Runner } from "./run.ts";

export const SERVICE_LABEL = "com.rudironsoni.herdr-orca-sync";

export type ServicePlatform = "darwin" | "linux" | "win32" | string;

export type ServiceFs = {
  home: string;
  platform: ServicePlatform;
  write: (path: string, text: string) => void;
  chmod: (path: string, mode: number) => void;
  remove: (path: string) => void;
  mkdirp: (path: string) => void;
};

export function defaultShimPath(home = homedir()): string {
  return join(home, ".local/bin/herdr-orca");
}

export function launchdPlistPath(home = homedir()): string {
  return join(home, "Library/LaunchAgents", `${SERVICE_LABEL}.plist`);
}

export function systemdUnitPath(home = homedir()): string {
  return join(home, ".config/systemd/user/herdr-orca-sync.service");
}

export function renderShim(nodePath: string): string {
  const node = JSON.stringify(nodePath);
  const id = JSON.stringify(PLUGIN_ID);
  return `#!/bin/sh
# Generated by herdr-orca daemon ensure. Resolves the plugin root at launch.
set -e
NODE=${node}
PLUGIN_ID=${id}
if [ -n "\${HERDR_PLUGIN_ROOT:-}" ] && [ -f "\$HERDR_PLUGIN_ROOT/dist/herdr-orca.mjs" ]; then
  exec "$NODE" "\$HERDR_PLUGIN_ROOT/dist/herdr-orca.mjs" "$@"
fi
ROOT=$(herdr plugin list --plugin "$PLUGIN_ID" --json 2>/dev/null | python3 -c 'import json,sys; d=json.load(sys.stdin); rows=(d.get("result") or {}).get("plugins") or []; print(rows[0]["plugin_root"] if rows else "")')
if [ -z "$ROOT" ] || [ ! -f "$ROOT/dist/herdr-orca.mjs" ]; then
  echo "herdr-orca: plugin dist not found. Run herdr plugin install rudironsoni/herdr-orca" >&2
  exit 1
fi
exec "$NODE" "$ROOT/dist/herdr-orca.mjs" "$@"
`;
}

export function renderLaunchdPlist(opts: { home: string; shimPath: string; pathValue: string }): string {
  const log = join(opts.home, ".local/state/herdr/plugins", PLUGIN_ID, "daemon.log");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${SERVICE_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${opts.shimPath}</string>
    <string>daemon</string>
    <string>--foreground</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key><false/>
  </dict>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>${opts.pathValue}</string>
  </dict>
  <key>StandardOutPath</key><string>${log}</string>
  <key>StandardErrorPath</key><string>${log}</string>
</dict>
</plist>
`;
}

export function renderSystemdUnit(opts: { shimPath: string; pathValue: string }): string {
  return `[Unit]
Description=herdr-orca-sync
After=default.target

[Service]
ExecStart=${opts.shimPath} daemon --foreground
Restart=on-failure
Environment=PATH=${opts.pathValue}

[Install]
WantedBy=default.target
`;
}

export function pathForService(home: string, platform: ServicePlatform, envPath: string): string {
  const extras = [join(home, ".local/bin"), "/opt/homebrew/bin", "/usr/local/bin"];
  const parts = [...extras, envPath || "/usr/bin:/bin"].join(":");
  if (platform === "darwin") return parts;
  return parts;
}

export function installServiceFiles(opts: {
  fs: ServiceFs;
  nodePath: string;
  envPath: string;
}): { shimPath: string; unitPath: string | null } {
  const shimPath = defaultShimPath(opts.fs.home);
  opts.fs.mkdirp(dirname(shimPath));
  opts.fs.write(shimPath, renderShim(opts.nodePath));
  opts.fs.chmod(shimPath, 0o755);
  const pathValue = pathForService(opts.fs.home, opts.fs.platform, opts.envPath);
  if (opts.fs.platform === "darwin") {
    const unitPath = launchdPlistPath(opts.fs.home);
    opts.fs.mkdirp(dirname(unitPath));
    opts.fs.write(unitPath, renderLaunchdPlist({ home: opts.fs.home, shimPath, pathValue }));
    return { shimPath, unitPath };
  }
  if (opts.fs.platform === "linux") {
    const unitPath = systemdUnitPath(opts.fs.home);
    opts.fs.mkdirp(dirname(unitPath));
    opts.fs.write(unitPath, renderSystemdUnit({ shimPath, pathValue }));
    return { shimPath, unitPath };
  }
  return { shimPath, unitPath: null };
}

export function removeServiceFiles(fs: ServiceFs): void {
  fs.remove(defaultShimPath(fs.home));
  fs.remove(launchdPlistPath(fs.home));
  fs.remove(systemdUnitPath(fs.home));
}

export function loadUserService(opts: { platform: ServicePlatform; home: string; run: Runner }): void {
  if (opts.platform === "darwin") {
    const plist = launchdPlistPath(opts.home);
    const uid = String(process.getuid?.() ?? "");
    opts.run(["launchctl", "bootout", `gui/${uid}`, plist]);
    opts.run(["launchctl", "bootstrap", `gui/${uid}`, plist]);
    opts.run(["launchctl", "kickstart", "-k", `gui/${uid}/${SERVICE_LABEL}`]);
    return;
  }
  if (opts.platform === "linux") {
    opts.run(["systemctl", "--user", "daemon-reload"]);
    opts.run(["systemctl", "--user", "enable", "--now", "herdr-orca-sync.service"]);
  }
}

export function unloadUserService(opts: { platform: ServicePlatform; home: string; run: Runner }): void {
  if (opts.platform === "darwin") {
    const uid = String(process.getuid?.() ?? "");
    opts.run(["launchctl", "bootout", `gui/${uid}`, launchdPlistPath(opts.home)]);
    return;
  }
  if (opts.platform === "linux") {
    opts.run(["systemctl", "--user", "disable", "--now", "herdr-orca-sync.service"]);
  }
}

export function defaultServiceFs(home = homedir(), platform: ServicePlatform = process.platform): ServiceFs {
  return {
    home,
    platform,
    write: (path, text) => {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, text);
    },
    chmod: (path, mode) => chmodSync(path, mode),
    remove: (path) => {
      try {
        unlinkSync(path);
      } catch {
        /* gone */
      }
    },
    mkdirp: (path) => mkdirSync(path, { recursive: true }),
  };
}
